
--QUESTION 1/ WRITE A QUERY TO FIND THE TOTAL SALES AMOUNT AND THE AVERAGE ORDER AMOUNT FOR EACH SALESPERSON IN EACH YEAR. 
-- ORDER THE RESULTS BY YEAR, SALESPERSON NAME, AND TOTAL SALES AMOUNT IN DESCENDING ORDER.

WITH CTE AS (SELECT EMPLOYEEID, YEAR(REQUIREDDATE) AS THE_YEAR,ROUND(SUM (UNITPRICE*QUANTITY*(1-DISCOUNT)),1) AS TOTALSALE
FROM [NORTHWND].[DBO].[ORDERS] O JOIN [NORTHWND].[DBO].[ORDER DETAILS] D ON O.ORDERID=D.ORDERID
GROUP BY EMPLOYEEID, YEAR(REQUIREDDATE))

SELECT CONCAT(FIRSTNAME, ' ', LASTNAME) AS FULLNAME, THE_YEAR, TOTALSALE
FROM [NORTHWND].[DBO].[EMPLOYEES] E JOIN CTE ON E.EMPLOYEEID=CTE.EMPLOYEEID
ORDER BY THE_YEAR, TOTALSALE DESC


-- Q2: WRITE A QUERY TO FIND THE TOP THREE PRODUCTS IN EACH CATEGORY BASED ON THE TOTAL REVENUE.
--ORDER THE RESULTS BY CATEGORY_ID, QUANTITY, AND PRODUCT_NAME IN DESCENDING ORDER.
WITH A1 AS (SELECT PRODUCTID, ROUND(SUM (UNITPRICE*QUANTITY*(1-DISCOUNT)),1) AS REVENUE
FROM NORTHWND. [DBO].[ORDER DETAILS]
GROUP BY PRODUCTID)
,
A2 AS (SELECT CATEGORYID, A1.PRODUCTID, REVENUE, DENSE_RANK() OVER (PARTITION BY CATEGORYID ORDER BY REVENUE DESC) AS THE_ROW
FROM A1 JOIN NORTHWND.[DBO].[PRODUCTS] P ON A1.PRODUCTID=P.PRODUCTID)

SELECT A2.CATEGORYID, PRODUCTNAME, REVENUE
FROM A2 JOIN NORTHWND.[DBO].[PRODUCTS] P ON A2.PRODUCTID=P.PRODUCTID
WHERE THE_ROW <4

-- NOTE: USE DENSE_RANK AND NOT RANK (BECAUSE MANY PRODUCTS HAVE THE SAME REVENUE, RANK WILL HAVE THE SAME SEQUENTIAL NUMBER BUT THE NUMBER WILL BE JUMPED DUE TO ROWNUMBER (BECAUSE THERE MAY BE MANY PRODUCTS WITH THE SAME REVENUE).

-- Q3: WRITE A QUERY TO FIND THE PERCENTAGE OF ORDERS THAT WERE PLACED BY CUSTOMERS FROM EACH COUNTRY. 
-- ROUND THE PERCENTAGE TO TWO DECIMAL PLACES. ORDER THE RESULTS BY PERCENTAGE IN DESCENDING ORDER.
WITH A AS (SELECT O.ORDERID, COUNTRY
FROM [NORTHWND].[DBO].[ORDERS] O JOIN [NORTHWND].[DBO].[ORDER DETAILS] D ON O.ORDERID=D.ORDERID 
	JOIN [NORTHWND].[DBO].[CUSTOMERS] C ON O.CUSTOMERID=C.CUSTOMERID)
,
B AS (SELECT DISTINCT COUNTRY AS THE_COUNTRY, CAST(COUNT(ORDERID) OVER (PARTITION BY COUNTRY) AS DECIMAL) AS C1, 
CAST (COUNT(ORDERID) OVER () AS DECIMAL) AS C2
FROM A)

SELECT THE_COUNTRY, CAST(C1*100/C2 AS DECIMAL(5,3)) AS PERCENTAGE
FROM B
ORDER BY PERCENTAGE DESC

-- NOTE: YOU MUST CAST BOTH THE NUMẺATOR AND THE DEMITTER FIRST FOR THE RESULT TO BE DECIMAL. CAST RESULTS HAVE NO EFFECT.

-- ANOTHER SOLUTION USING COUNT AND SUM:
WITH CTE AS (
  SELECT 
    [COUNTRY], 
    COUNT(ORDERID) AS [ORDERCOUNT]
  FROM [NORTHWND].[DBO].[ORDERS] AS O
  JOIN [NORTHWND].[DBO].[CUSTOMERS] AS C
    ON O.[CUSTOMERID] = C.[CUSTOMERID]
  GROUP BY [COUNTRY]
)
SELECT 
  [COUNTRY], 
  ROUND([ORDERCOUNT] * 100.0 / (SELECT SUM([ORDERCOUNT]) FROM CTE), 2) AS [PERCENTAGE]
FROM CTE
ORDER BY [PERCENTAGE] DESC;

-- Q4: WRITE A QUERY TO FIND THE MONTHLY GROWTH RATE OF SALES FOR EACH CATEGORY IN EACH YEAR. 
-- CALCULATE THE MONTHLY GROWTH RATE AS THE PERCENTAGE CHANGE IN SALES FROM THE PREVIOUS MONTH TO THE CURRENT MONTH, USING THE FORMULA: (CURRENT_MONTH_SALES - PREVIOUS_MONTH_SALES) / PREVIOUS_MONTH_SALES * 100. 
-- ROUND THE GROWTH RATE TO TWO DECIMAL PLACES. 

WITH CTE AS (SELECT DISTINCT YEAR(ORDERDATE) AS YEAR, MONTH(ORDERDATE) AS MONTH, CATEGORYNAME AS CATEGORY, 
SUM(D.UNITPRICE*QUANTITY*(1-DISCOUNT)) OVER (PARTITION BY YEAR(ORDERDATE), MONTH(ORDERDATE), CATEGORYNAME) AS MONTHSALE
FROM [DBO].[ORDERS] O 
JOIN [DBO].[ORDER DETAILS] D ON O.ORDERID=D.ORDERID 
JOIN [DBO].[PRODUCTS] P ON D.PRODUCTID=P.PRODUCTID 
JOIN [DBO].[CATEGORIES] C ON P.CATEGORYID=C.CATEGORYID)
SELECT *, ROUND((MONTHSALE - LAG(MONTHSALE) OVER (PARTITION BY CATEGORY, YEAR ORDER BY MONTH)) / LAG(MONTHSALE) OVER (PARTITION BY CATEGORY,YEAR ORDER BY MONTH) * 100, 2) AS GROWTH
FROM CTE
ORDER BY CATEGORY, YEAR, MONTH

-- NOTE: TO PARTITION CORRECTLY: TO GET LAG, FIRST WE MUST RE-ORDER BY CATEGORY, IN CATEGORY WE MUST RE-ORDER BY YEAR.
-- NO NEXT PARTITION MONTH BECAUSE IF SO WHAT IS THE LAG. IN THE CATEGORY AND YEAR COMPARTMENTS YOU MUST ARRANGE BY MONTH TO GET THE CORRECT LAG.

-- Q5: WRITE A QUERY TO FIND THE MOST POPULAR PRODUCT IN EACH MONTH BASED ON THE NUMBER OF ORDERS.
WITH CTE AS (SELECT DISTINCT YEAR(ORDERDATE) AS YEAR, MONTH(ORDERDATE) AS MONTH, PRODUCTNAME AS PRODUCT
, COUNT(O.ORDERID) OVER (PARTITION BY YEAR(ORDERDATE), MONTH(ORDERDATE), PRODUCTNAME) AS NUMBER_OF_ORDER
FROM [DBO].[ORDERS] O 
JOIN [DBO].[ORDER DETAILS] D ON O.ORDERID=D.ORDERID 
JOIN [DBO].[PRODUCTS] P ON D.PRODUCTID=P.PRODUCTID )
,
CTE2 AS (SELECT YEAR, MONTH, PRODUCT, NUMBER_OF_ORDER
, RANK() OVER (PARTITION BY YEAR, MONTH ORDER BY NUMBER_OF_ORDER DESC) AS THERANK
FROM CTE)
-- USE RANK INSTEAD OF ROW_NUMBER BECAUSE THERE MAY BE MANY PRODUCTS WITH EQUAL ORDER NUMBERS AND THE HIGHEST.

SELECT YEAR, MONTH, PRODUCT AS MOSTPOPULARPRODUCT
FROM CTE2
WHERE THERANK=1;


